config/routes.rb
Rails.application.routes.draw do
  
  get 'academies/show'
  get 'products/show'
  get 'projects/show'
  get 'courses/show'
  get 'quotes/show'
  get 'events/show'
  get 'events/index'
  get 'home/show'
  root 'home#show'
  resources :events, :only => [:show, :index]
  resources :downloads, :only => [:show, :index]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
end

app/models/academy.rb
class Academy < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :downloads
	validates :name, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/download.rb
class Download < ApplicationRecord
	belongs_to :category

	def self.search(search)
		#where("category_id LIKE '?'", "%#{search}")
		where("category_id::text LIKE ?", "%#{search}")
		#where(category_id: %search)
	end
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :product_family
end

app/models/product_family.rb
class ProductFamily < ApplicationRecord
	has_many :products
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  def index
  	if params[:download] and params[:download][:category_id]
  		@downloads = Download.search(params[:download][:category_id])
  	else
  		@downloads = Download.all.order("created_at DESC")
  	end 
  end

  def show 
  	@download = Download.find(params[:id])
  end

  def download_params
  	params.require(:download).permit(:name, :url, :category_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def show
		@event = Event.find(params[:id])
	end

	def index
		@events = Event.all.order('created_at DESC')
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def show
	 	@events = Event.all
	 	@products = Product.all
	 	@quotes = Quote.all
	end
end

app/helpers/academies_helper.rb
module AcademiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/downloads/index.html.erb
<%= render 'layouts/navigation' %>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active ">
      <img class="d-block w-100" src="https://res.cloudinary.com/inddev/image/upload/v1541187150/download-1.jpg" alt="First slide">
      <div class="carousel-caption d-none d-md-block">
	  	<h5>All the resources</h5>
      <p>Collected for your convenience!</p>
  	</div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://res.cloudinary.com/inddev/image/upload/v1541187543/download-2.png" alt="Second slide">
      <div class="carousel-caption d-none d-md-block">
	  	<h5>No more waiting for infomration</h5>
      <p>Everything just a few clicks away!</p>
  	</div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://res.cloudinary.com/inddev/image/upload/v1541187542/download-3.jpg" alt="Third slide">
      <div class="carousel-caption d-none d-md-block">
	  	<h5>Downloads Directory</h5>
      <p>Explore Now</p>
  	</div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<div class="downloads-selection-area">
<h5>What kind of download are you looking for?</h5>
<%= form_tag downloads_path, :method => 'get' do %>
	<%= collection_select :download, :category_id, Category.all, :id, :name, prompt: true %>
	<%= submit_tag "Filter" %>
<% end %>
</div>
<div class="filtered-files-area">
	
<p><strong>Downloads as per your current selection:-<br></strong></p>
<% @downloads.each do |d| %>
	<h4>File Name: <%= d.name %><br></h4>
	Category: <%= d.category.name %><br>
	<hr>
<% end %>
</div>

<%= render 'layouts/footer' %>

app/views/downloads/show.html.erb
<%= render 'layouts/navigation' %>
	<%= @download.name %><br>
	<%= @download.category.name %><br>	

<%= render 'layouts/footer' %>