config/routes.rb
Rails.application.routes.draw do
  
  get 'academies/show'
  get 'products/show'
  get 'projects/show'
  get 'courses/show'
  get 'quotes/show'
  get 'events/show'
  get 'events/index'
  get 'home/show'
  root 'home#show'
  resources :events, :only => [:show, :index]
  resources :downloads, :only => [:show, :index]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
end

app/models/academy.rb
class Academy < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :downloads
	validates :name, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/download.rb
class Download < ApplicationRecord
	belongs_to :category

	def self.search(search)
		#where("category_id LIKE '?'", "%#{search}")
		where("category_id::text LIKE ?", "%#{search}")
		#where(category_id: %search)
	end
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :product_family
end

app/models/product_family.rb
class ProductFamily < ApplicationRecord
	has_many :products
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def show
		@event = Event.find(params[:id])
	end

	def index
		@events = Event.all.order('created_at DESC')
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def show
	 	@events = Event.all
	 	@products = Product.all
	 	@quotes = Quote.all
	end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def show
  end
end

app/helpers/academies_helper.rb
module AcademiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/events/index.html.erb
<%= render 'layouts/navigation' %>

<div class="jumbotron">
  <h1 class="display-4">Keep updated on all the latest events!</h1>
  <p class="lead">Welcome to MyMerino Portal.</p>
  <hr class="my-4">
  <p>Your new home for- Product related information, Training, Certifications, Company Events and so much more! Click below to learn more about My Merino</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>


<% @events.each do |event| %>
	<h3><%= event.title %></h3>
	<a class= "list-group-item list-group-item-action" href="<%= event.url %>">Image Link</a>
<% end %>
<hr>

<% @events.each do |event| %>
<div class="well">
	<h3><%= event.title  %></h3>
	<p><%= event.url %></p>
	<%= link_to "Read More", event_path(event), :class =>'btn-primary' %>
	<% end %>
</div>

<%= render 'layouts/footer' %>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>
<hr>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			Hello, <%= @event.title %>
		</h1>
	</div>
</div>


<%= render 'layouts/footer' %>

app/views/quotes/show.html.erb
<%= render 'layouts/navigation' %>

<h1>Quotes#show</h1>
<p>Find me in app/views/quotes/show.html.erb</p>