config/routes.rb
Rails.application.routes.draw do
  
  get 'academies/show'
  get 'products/show'
  get 'projects/show'
  get 'courses/show'
  get 'quotes/show'
  get 'events/show'
  get 'events/index'
  get 'home/show'
  root 'home#show'
  resources :events, :only => [:show, :index]
  resources :downloads, :only => [:show, :index]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
end

app/models/academy.rb
class Academy < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :downloads
	validates :name, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/download.rb
class Download < ApplicationRecord
	belongs_to :category

	def self.search(search)
		#where("category_id LIKE '?'", "%#{search}")
		where("category_id::text LIKE ?", "%#{search}")
		#where(category_id: %search)
	end
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :product_family
end

app/models/product_family.rb
class ProductFamily < ApplicationRecord
	has_many :products
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def show
		@event = Event.find(params[:id])
	end

	def index
		@events = Event.all.order('created_at DESC')
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def show
	 	@events = Event.all
	 	@products = Product.all
	 	@quotes = Quote.all
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
	 	@products = Product.all
	end
end

app/helpers/academies_helper.rb
module AcademiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/products/show.html.erb
<%= render 'layouts/navigation' %>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active ">
      <img class="d-block w-100" src="https://res.cloudinary.com/inddev/image/upload/v1540882919/antifinger-banner.jpg" alt="First slide">
      <div class="carousel-caption d-none d-md-block">
	  	<h5>Antifinger Laminates</h5>
      <p>So smooth!</p>
  	</div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://res.cloudinary.com/inddev/image/upload/v1540882919/imagino-banner.jpg" alt="Second slide">
      <div class="carousel-caption d-none d-md-block">
	  	<h5>Imagino</h5>
      <p>Unleash your imagination!</p>
  	</div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://res.cloudinary.com/inddev/image/upload/v1540882919/superclad-banner.jpg" alt="Third slide">
      <div class="carousel-caption d-none d-md-block">
	  	<h5>Superclad by Merino</h5>
      <p>The power of creation!</p>
  	</div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<br>
<div class="product-grid">
	<br><h3 align="center">Product Database</h3>
	<div class="grid-subtext text-center justify-content-center">
	<p>Navigate to any product listed below to find detailed information about it. The product information is divided into technical and design sections. Some of the areas covered in these sections include-</p>
	<ul class="grid-subtext-ul">
		<li style="text-align:left">How laminates are made</li>
		<li style="text-align:left">How laminates are installed</li>
		<li style="text-align:left">Technical Specifications, Product Features</li>
		<li style="text-align:left">Certifications and Sustainability</li>
		<li style="text-align:left">Sizes, thickness and grades</li>
	</ul>
	<p>Please note that this information is kept upto date on a best effort basis.</p>
	</div>
	<div class="col-8 container border border-secondary" padding="50px">
		<h5 align="center">HPL Based Products</h5>
		  <ul class="list-unstyled row">
			<% @products.each do |product| %>
		    	<li class="list-item col-2 border-top border-bottom py-2"><%= link_to product.name, products_show_path %></li>
		    <% end %>
		  </ul>
	</div>
	<br>
	<br>	
	<div class="col-8 container border border-secondary" padding="50px">
		<h4 align="center">Compacts Based Products</h4>
			<% @products.each do |product, i| %>
				<%= product.name %>
		    <% end %>
	</div>
</div>

<%= render 'layouts/footer' %>