config/routes.rb
Rails.application.routes.draw do
  
  get 'academies/show'
  get 'products/show'
  get 'projects/show'
  get 'courses/show'
  get 'quotes/show'
  get 'events/show'
  get 'events/index'
  get 'home/show'
  root 'home#show'
  resources :events, :only => [:show, :index]
  resources :downloads, :only => [:show, :index]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
end

app/models/academy.rb
class Academy < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :downloads
	validates :name, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/download.rb
class Download < ApplicationRecord
	belongs_to :category

	def self.search(search)
		#where("category_id LIKE '?'", "%#{search}")
		where("category_id::text LIKE ?", "%#{search}")
		#where(category_id: %search)
	end
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :product_family
end

app/models/product_family.rb
class ProductFamily < ApplicationRecord
	has_many :products
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/helpers/academies_helper.rb
module AcademiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_footer.html.erb
<footer class="pt-5 pb-4" id="contact">
			<div class="container">
				<div class="row">
					<div class="col-lg-3 col-md-6 col-sm-6 mt-2 mb-4">
						<h5 class="mb-4 font-weight-bold">ABOUT US</h5>
						<p class="mb-4">Economy. Excellence. Ethics.</p>
						<ul class="f-address">
							<li>
								<div class="row">
									<div class="col-1"><i class="fas fa-map-marker"></i></div>
									<div class="col-10">
										<h6 class="font-weight-bold mb-0">Address:</h6>
										<p>KLJ Complex, Moti Nagar, Delhi</p>
									</div>
								</div>
							</li>
							<li>
								<div class="row">
									<div class="col-1"><i class="far fa-envelope"></i></div>
									<div class="col-10">
										<h6 class="font-weight-bold mb-0">Have any questions?</h6>
										<p><a href="#">contactus@merinoindia.com</a></p>
									</div>
								</div>
							</li>
							<li>
								<div class="row">
									<div class="col-1"><i class="fas fa-phone-volume"></i></div>
									<div class="col-10">
										<h6 class="font-weight-bold mb-0">Call Us:</h6>
										<p><a href="#">+91 (0) 11XXXXX</a></p>
									</div>
								</div>
							</li>
						</ul>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 mt-2 mb-4">
						<h5 class="mb-4 font-weight-bold">FRESH TWEETS</h5>
						<ul class="f-address">
							<li>
								<div class="row">
									<div class="col-1"><i class="fab fa-twitter"></i></div>
									<div class="col-10">
										<p class="mb-0"><a href="#">@XYZ1 </a> Tweet No 1</p>
										<label>10 Mins Ago</label>
									</div>
								</div>
							</li>
							<li>
								<div class="row">
									<div class="col-1"><i class="fab fa-twitter"></i></div>
									<div class="col-10">
										<p class="mb-0"><a href="#">@XYZ2 </a>Tweet No 2</p>
										<label>10 Mins Ago</label>
									</div>
								</div>
							</li>
							<li>
								<div class="row">
									<div class="col-1"><i class="fab fa-twitter"></i></div>
									<div class="col-10">
										<p class="mb-0"><a href="#">@XYZ3 </a> Tweet No 3</p>
										<label>10 Mins Ago</label>
									</div>
								</div>
							</li>
						</ul>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 mt-2 mb-4">
						<h5 class="mb-4 font-weight-bold">LATEST UPDATES</h5>
						<ul class="recent-post">
							<li>
								<label class="mr-3">28 <br><span>APR</span></label>
								<span>New Experience Center.</span>
							</li>
							<li>
								<label class="mr-3">29 <br><span>APR</span></label>
								<span>Sales Meet.</span>
							</li>
						</ul>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6 mt-2 mb-4">
						<h5 class="mb-4 font-weight-bold">CONNECT WITH US</h5>
						<div class="input-group">
						  	<input type="text" class="form-control" placeholder="Your Email Address">
						  	<span class="input-group-addon" id="basic-addon2"><i class="fas fa-check"></i></span>
						</div>
						<ul class="social-pet mt-4">
							<li><a href="#" title="facebook"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#" title="twitter"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#" title="google-plus"><i class="fab fa-google-plus-g"></i></a></li>
							<li><a href="#" title="instagram"><i class="fab fa-instagram"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</footer>
		<!-- Copyright -->
		<section class="copyright">
			<div class="container">
				<div class="row">
					<div class="col-md-12 ">
						<div class="text-center text-white">
							&copy; 2018 Merino India Pvt Ltd. All Rights Reserved.
						</div>
					</div>
				</div>
			</div>
		</section>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  	<a class="navbar-brand" href="www.merinoindia.com"><img class="navbar-logo-img" src="https://res.cloudinary.com/inddev/image/upload/v1540676780/Merino-Group-Logo.png" alt="Ethics Economy Excellence">
	</a>
  <a class="navbar-brand" href="#">MyMerino Portal</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="<%= root_url %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= products_show_url %>" data-toggle="tooltip" data-placement="top" title="Look up Merino's products">Product Database</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= academies_show_url %>" data-toggle="tooltip" data-placement="top" title="Learn and get certified">Merino Academy</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= downloads_url %>" data-toggle="tooltip" data-placement="top" title="Learn and get certified">Downloads</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= events_url %>" data-toggle="tooltip" data-placement="top" title="For our special partners">Humrahi Zone</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= projects_show_url %>" data-toggle="tooltip" data-placement="top" title="Some of our best work">Our Projects</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= events_url %>" data-toggle="tooltip" data-placement="top" title="Get to know about our latest events">Events</a>
      </li>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

    <ul class="nav navbar-nav navbar-right">
            <!-- PROFILE DROPDOWN - scrolling off the page to the right -->
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" id="navDropDownLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Profile
                </a>
                <div class="dropdown-menu" aria-labelledby="navDropDownLink">
                    <a class="dropdown-item" href="#">Preferences</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Logout</a>
                </div>
            </li>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mymerinoapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>